### ISSUE TITLE
person_fn parameter is not null by default

### ISSUE THREAD

**Issue by zinkovskiy** [OxCom/symfony3-rollbar-bundle#16]
Hello, guys. I have a question about `person_fn` config parameter. Why is it null by default?
Why don't you define a class like this by default:

```
class PersonProvider implements InterfacePersonProvider
{
    /** @var TokenStorageInterface */
    private $tokenStorage;

    public function __construct(TokenStorageInterface $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    public function getPerson(): array
    {
        if ($token = $this->tokenStorage->getToken()) {
            $user = $token->getUser();
            if (!$user || !is_object($user)) {
                return [];
            }

            $userData = [];
            if (method_exists($user, 'getId')) {
                $userData['id'] = $user->getId();
            } else {
                // id is required
                $userData['id'] = $user->getUsername();
            }

            $userData['username'] = $user->getUsername();
            if (method_exists($user, 'getEmail')) {
                $userData['email'] = $user->getEmail();
            }

            return $userData;
        }

        return [];
    }
}
```

So, it would be convenient for a lot of users, because they don't need to create own service to get user data. It's better than nothing, isn't it? 
And of course they can override it, if they would need some additional data.

**Comment by OxCom** [comment]
@zinkovskiy I need more time to think on this. Idea is good, but I would like to think more on realisation.

**Comment by OxCom** [comment]
In general:
- There few restrictions to support this for multiple versions of Symfony like (DI, accessebility and e.t.c.).
- I will modify AbstractPersonProvider to drop ```__construct``` method to make this class more flexiable, but I think that this class is redundent.
- Finaly I think that it's up to developer to decide how to provide person info, because there such things like: GDPR, no authorization, authorization done in another way and e.t.c.

Base on this we have to provide only interface. That will provide developers with flexibility in ther projects and make flow more transparent.
